notedrop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main.views import feed, select_course, post_course, course_form, profile, post_options, users, posts, post_delete, starred, note_drop
from authentication.views import login_user, logout_user, signup


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', feed, name='feed'),
    url(r'^posts/(?P<post_pk>[0-9]+)/$', posts, name='posts'),
    url(r'^posts/delete/(?P<post_pk>[0-9]+)/$', post_delete, name='post_delete'),
    url(r'^users/(?P<username>[a-zA-Z0-9-@]+)/$', users, name='users'),
    url(r'^starred/$', starred, name='starred'),
    url(r'^courses/$', select_course, name='state_selection'),
    url(r'^courses/(?P<state>[a-zA-Z- ]+)/$', select_course, name='school_selection'),
    url(r'^courses/(?P<state>[a-zA-Z- ]+)/(?P<school>[a-zA-Z- ]+)/$', select_course, name='designator_selection'),
    url(r'^courses/(?P<state>[a-zA-Z- ]+)/(?P<school>[a-zA-Z- ]+)/(?P<designator>[a-zA-Z]+)/$', select_course, name='course_selection'),
    url(r'^post-course/$', post_course, name='post_course'),
    url(r'^post-note/$', note_drop, name='note_drop'),
    url(r'^post-options/', post_options, name='post_options'),
    url(r'^course-form/', course_form, name='course_form'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^login/', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^helm/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import uuid
import os
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    courses = models.ManyToManyField('Course', db_table='enrolled_courses')
    notify_count = models.PositiveIntegerField(default=0)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '{0} {1}'.format(self.user.first_name, self.user.last_name)


class Course(models.Model):
    school = models.ForeignKey('School')

    designator = models.CharField(max_length=3)
    number = models.CharField(max_length=3)
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return '{0} {1} {2}'.format(self.designator, self.number, self.name)


class School(models.Model):
    name = models.CharField(max_length=50)
    state = models.CharField(max_length=25)
    city = models.CharField(max_length=25)
    # TODO add image field for college stamp, stamp will be gotten via API

    def __unicode__(self):
        return self.name


class Post(models.Model):

    def get_img_path(self, filename):
        ext = filename.split('.')[-1]
        filename = "{name}.{ext}".format(name=uuid.uuid4(), ext=ext)
        return os.path.join('imgs', filename)

    author = models.ForeignKey(User)

    course = models.ForeignKey('Course')
    content = models.TextField()
    image = models.ImageField(upload_to=get_img_path, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __unicode__(self):
        if len(self.content) > 200:
            return "{0}..".format(self.content[:200])
        else:
            return self.content

    @property
    def rating(self):
        count = 0
        for p in PostData.objects.filter(post=self):
            if p.upvote is True:
                count += 1
            elif p.upvote is False:
                count -= 1
        return count

class PostData(models.Model):
    # TODO rename this to NoteData
    post = models.ForeignKey('Post')
    user = models.ForeignKey(User)

    upvote = models.NullBooleanField(default=None)
    noted = models.NullBooleanField(default=False)
    notified = models.NullBooleanField(default=False)
    modified = models.DateTimeField(auto_now=True)

# property to get related UserProfile from a User
User.profile = property(lambda user_id: UserProfile.objects.get_or_create(user=user_id)[0])

main/forms.py
from django import forms

from .models import Course, UserProfile, Post


class PostForm(forms.ModelForm):
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 50}))

    class Meta:
        model = Post
        fields = ('course', 'content', 'image')
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(PostForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields["course"].queryset = user.profile.courses.all()


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('school', 'designator', 'number', 'name',)

    number = forms.IntegerField(min_value=1, max_value=999)

    def clean_designator(self):
        designator = self.cleaned_data['designator']
        if len(designator) < 3:
            raise forms.ValidationError(
                'Ensure this value has 3 characters.',
                code='ValueLengthError'
            )
        designator = designator.upper()
        return designator

    def clean_number(self):
        number = self.cleaned_data['number']

        if number / 100 >= 1:
            number = str(number)
        elif number / 10 >= 1:
            number = '0' + str(number)
        else:
            number = '00' + str(number)

        return number

    def clean_name(self):
        name = self.cleaned_data['name']
        name = name.title()
        return name

main/views.py
import json
import random

from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import widgets

from .models import School, Course, UserProfile, Post, PostData
from .forms import CourseForm, PostForm
from .filters import PostFilter


@login_required
def feed(request):
    context = {}
    posts = []
    f = PostFilter(request.GET, queryset=Post.objects.filter(archived=False,
                                                             course__in=request.user.profile.courses.all()).order_by('-created'),
                                                             user=request.user)

    for p in f:
        post_data, created = PostData.objects.get_or_create(post=p, user=request.user)
        posts.append({
            'obj': p,
            'noted': post_data.noted,
            'upvote': post_data.upvote
        })

    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    def gen_hex_color_code():
        return ''.join([random.choice('0123456789ABCDEF') for x in range(6)])

    chart_data = []
    for course in request.user.profile.courses.all():
        chart_data.append({
            'value': Post.objects.filter(course=course).count(),
            'label': course.name,
            'color': '#' + gen_hex_color_code(),
            'highlight': '#' + gen_hex_color_code(),
        })

    context['chart_data'] = json.dumps(chart_data)
    context['posts'] = posts
    form = PostForm(user=request.user)
    if 'course' in request.GET:
        form.fields['course'].initial = request.GET['course']
    context['form'] = form
    context['filter'] = f
    return render(request, 'main/feed.html', context)


@login_required
def note_drop(request):
    referer =  request.META.get('HTTP_REFERER', None)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        errors = []
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            return HttpResponse(referer)
        else:
            for k, v in form.errors.as_data().iteritems():
                field = k.title()
                for msg in v:
                    errors.append('{field}: {msg}'.format(field=field, msg=str(msg[0])))
            return HttpResponseBadRequest(json.dumps(errors))

@login_required
def profile(request, username=None):
    context = {}
    if request.is_ajax():
        if request.POST.get('course_pk', None):
            course = Course.objects.get(pk=request.POST['course_pk'])
            if request.POST['action'] == 'Unfollow':
                request.user.profile.courses.remove(course)
            else:
                request.user.profile.courses.add(course)
            schools = School.objects.filter(pk__in=request.user.profile.courses.all().values('school').distinct())
            data = serializers.serialize('json', schools, fields=('name','state', 'city',))
            return HttpResponse(data)

        if request.POST.get('notify_count', None):
            profile = UserProfile.objects.get(user=request.user)
            profile.notify_count = request.POST['notify_count']
            profile.save()
            return HttpResponse(profile.notify_count)

    context['notify_count'] = request.user.profile.notify_count
    context['posts'] = Post.objects.filter(archived=False, author=request.user)
    context['schools'] = School.objects.filter(pk__in=request.user.profile.courses.all().values('school').distinct())
    context['courses'] = request.user.profile.courses.all()
    return render(request, 'main/profile.html', context)

@login_required
def select_course(request, state=None, school=None, designator=None):
    context = {}
    if designator and school and state:
        school_str = school.replace('-', ' ')
        courses = Course.objects.filter(designator__icontains=designator).exclude(userprofile__user=request.user)
        courses_users = []
        for c in courses:
            courses_users.append([c, UserProfile.objects.filter(courses=c).count()])

        context['courses_users'] = courses_users
        context['school'] = school = School.objects.filter(name__icontains=school_str)[0]
        context['designator'] = designator
        return render(request, 'main/courses.html', context)

    if school and state:
        school_str = school.replace('-', ' ')
        school = School.objects.filter(name__icontains=school_str)[0]
        context['school'] = school
        context['designators'] = Course.objects.filter(school=school).values_list('designator', flat=True).distinct().order_by('designator')
        return render(request, 'main/designators.html', context)

    if state:
        state_str = state.replace('-', ' ')
        schools = School.objects.filter(state__icontains=state_str).order_by('name')
        context['schools'] = schools
        return render(request, 'main/schools.html', context)

    context['states'] = School.objects.values_list('state', flat=True).distinct().order_by('state')
    return render(request, 'main/states.html', context)

@login_required
def post_course(request):
    if request.is_ajax():
        course = Course.objects.get(pk=request.POST['course_pk'])
        if request.POST['action'] == 'Unfollow':
            request.user.profile.courses.remove(course)
        else:
            request.user.profile.courses.add(course)
        return HttpResponse('success')
    return HttpResponseBadRequest('error')

@login_required
def course_form(request):
    context = {}
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.save()
            request.user.profile.courses.add(course)
            return redirect('feed')
        else:
            context['errors'] = form.errors
            context['form'] = form
            return render(request, 'main/course_form.html', context)

    form = CourseForm()
    if 'school' in request.GET:
        school_str = request.GET['school'].replace('-', ' ')
        school = School.objects.filter(name__icontains=school_str)
        if school:
            school = school[0]
            form.fields['school'].widget = widgets.HiddenInput()
            form.fields['school'].initial = school
            context['school'] = school

    if 'designator' in request.GET:
        designator = request.GET['designator'].upper()
        form.fields['designator'].initial = designator
        context['designator'] = designator

    context['form'] = form
    return render(request, 'main/course_form.html', context)

@login_required
def post_options(request):
    if 'noted_pk' in request.POST:
        post_data = PostData.objects.get(post=request.POST['noted_pk'], user=request.user)
        if post_data.noted is False:
            post_data.noted = True
        else:
            post_data.noted = False
        post_data.save()
        return HttpResponse(json.dumps(post_data.noted))

    if 'up_pk' in request.POST:
        post_data = PostData.objects.get(post=request.POST['up_pk'], user=request.user)
        if post_data.upvote is not True:
            post_data.upvote = True
        else:
            post_data.upvote = None
        post_data.save()
        return HttpResponse(json.dumps({'post_pk': post_data.post.pk, 'rating': post_data.post.rating, 'upvote': post_data.upvote}))

    if 'down_pk' in request.POST:
        post_data = PostData.objects.get(post=request.POST['down_pk'], user=request.user)
        if post_data.upvote is not False:
            post_data.upvote = False
        else:
            post_data.upvote = None
        post_data.save()
        return HttpResponse(json.dumps({'post_pk': post_data.post.pk, 'rating': post_data.post.rating, 'upvote': post_data.upvote}))

    return HttpResponseBadRequest()

@login_required
def users(request, username=None):
    context = {}
    q = UserProfile.objects.get(user__username=username)
    context['username'] = q.user.username
    context['posts'] = Post.objects.filter(author=q.user)
    context['courses'] = q.courses.all()
    context['schools'] = School.objects.filter(pk__in=q.courses.all().values('school').distinct())
    return render(request, 'main/users.html', context)

@login_required
def posts(request, post_pk=None):
    context = {}
    post = Post.objects.filter(pk=int(post_pk))
    if post:
        context['post'] = post[0]
    return render(request, 'main/posts.html', context)

def post_delete(request, post_pk=None):
    if post_pk:
        post_pk = int(post_pk)
        if any(p.pk == post_pk for p in Post.objects.filter(author=request.user)):
            post = Post.objects.get(pk=post_pk)
            post.archived = True
            post.save()

    return redirect('profile')

@login_required
def starred(request):
    context = {}
    context['posts'] = PostData.objects.filter(user=request.user, noted=True)
    return render(request, 'main/starred.html', context)

templates/main/course_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Add Course{% endblock %}

{% block content %}

{% if designator and school %}
  <h1 class='page-header'>Add {{ designator }} course for {{ school.name }}</h1>
{% elif school %}
  <h1 class='page-header'>Add course for {{ school.name }}</h1>
{% else %}
  <h1 class='page-header'>Add course</h1>
{% endif %}

{% if errors %}
  <div class="alert alert-danger">
    {{ errors }}
  </div>
{% endif %}

<form class='form-group' action='{% url 'course_form' %}' method='post'>
  {% csrf_token %}
    <label for='id_school'>{{ form.school.label }}</label>
    {% render_field form.school class+='form-control' %}
    <label for='id_designator'>{{ form.designator.label }}</label>
    {% render_field form.designator class+='form-control' %}
    <label for='id_number'>{{ form.number.label }}</label>
    {% render_field form.number class+='form-control' %}
    <label for='id_name'>{{ form.name.label }}</label>
    {% render_field form.name class+='form-control' %}
  <button class='btn btn-md btn-primary form-control' type='submit'>Add Course</button>
</form>

{% endblock %}

templates/main/courses.html
{% extends 'base.html' %}

{% block title %}Course Selection{% endblock %}

{% block content %}
<h1>Select the course you wish to follow</h1>

<table class='table'>
{% for course_user in courses_users %}
  <tr>
    <td>{{ course_user.0 }} ({{ course_user.1 }} users)</td>
    <td><button class='btn btn-md btn-default course-handler' value='{{ course_user.0.pk }}'>Follow</button></td>
  </tr>
{% endfor %}
</table>

<label>If you do not see your course <a href='{% url 'course_form' %}?school={{ school.name|slugify }}&designator={{ designator }}'>Add course?</a></label>
</br>
<label>All done? <a href='{% url 'feed' %}'>Go to Feed</a></label>

{% endblock %}

{% block extra_head %}
<script>
$(document).ready(function(){

  $('.course-handler').click(function(){
    var clickedButton = $(this);
    $.post('{% url 'post_course' %}', {'course_pk': $(this).val(), 'action': $(this).text()})
      .done(function(data){
        flip_button_action(clickedButton)
      });
  });
});

function flip_button_action(btn){
  if(btn.text() == 'Unfollow'){
    btn.text('Follow');
  }
  else {
    btn.text('Unfollow');
  }
}
</script>
{% endblock %}

templates/main/designators.html
{% extends 'base.html' %}

{% block title %}Course Designator Selection{% endblock %}

{% block content %}
<h1 class="page-header">Select the designator of your course</h1>

<ul>
{% for designator in designators %}
  <li><a href='{% url 'course_selection' state=school.state|slugify school=school.name|slugify designator=designator|slugify %}'>{{ designator }}</a></li>
{% endfor %}
</ul>

<label>If you do not see your course designator <a href='{% url 'course_form' %}?school={{ school.name|slugify }}'>Add course?</label>

{% endblock %}

templates/main/feed.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load widget_tweaks %}

{% block title %}Notedrop Feed{% endblock %}

{% block content %}

<div class='col-sm-8'>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Drop a Note</h4>
      </div>
      <div class="modal-body">

        <form enctype='multipart/form-data' id='note-drop-form' class='form-group'  method='post' action='{% url 'note_drop' %}'>
          <div id='note-drop-form-errors' class='alert alert-danger' hidden></div>
          {% csrf_token %}
            <label for='id_course'>{{ form.course.label }}</label>
            {% render_field form.course class+='form-control' %}
            <label for='id_content'>{{ form.content.label }}</label>
            {% render_field form.content class+='form-control' %}
            <label for="id_image">{{ form.image.label }}</label>
            {% render_field form.image class+='form-control' %}
            <p class="help-block">Image formats only (PNG, JPEG, TIFF, GIFF)</p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id='note-drop-submit' class='btn btn-primary'>Drop Note</button>
      </form>
      </div>
    </div>
  </div>
</div>

<div class='page-header'>
  <h2 id='header'>Note Feed</h2>
  <button id='drop-note-btn' class='btn btn-md btn-primary pull-right' data-toggle="modal" data-target="#myModal">Drop a Note</button>
</div>
{% if posts %}
  {% for post in posts %}
  <div class='post bg-success'>

    <div class='post-info bg-warning'>
      <span class='post-course bg-warning'>{{ post.obj.course }}</span>
      <span class='post-author'><a href='{% url 'users' username=post.obj.author %}'>{{ post.obj.author }}</a></span>
      <p class='post-content'><strong>{{ post.obj }}</strong></p>
      {% if post.obj.image %}
        <img src='/media/{{ post.obj.image }}' class='img-responsive post-image' />
      {% endif %}
      <em><span class='text-muted'>Created {{ post.obj.created }}</span></em>
      <a class='post-permalink' href='{% url 'posts' post_pk=post.obj.pk %}'>&#8734;</a>
    </div>

    <div class='post-options post-{{ post.obj.pk }}'>
      <button class='post-options-btn noted-btn' object='{{ post.obj.pk }}' {% if post.noted %}style='color: rgb(255, 145, 0);'{% endif %}>&#9733;</button>
      <button class='post-options-btn up-btn' object='{{ post.obj.pk }}' {% if post.upvote == True %}style='color: rgb(255, 145, 0);'{% endif %}>&#9650;</button>
      <span class='post-rating'>{{ post.obj.rating }}</span>
      <button class='post-options-btn down-btn' object='{{ post.obj.pk }}' {% if post.upvote == False %}style='color: rgb(255, 145, 0);'{% endif %}>&#9660;</button>
    </div>

  </div>
  {% endfor %}
  {% bootstrap_paginate posts show_prev_next="false" show_first_last="true" %}
{% else %}
  <div class='alert alert-warning'>
    No results
  </div>
{% endif %}
</div>
<!-- end of notefeed  -->

<aside class='col-sm-4 well'>
  <a href='{% url 'feed' %}' class='btn btn-sm btn-default pull-right'>Clear</a>
  <span class='well-header'>Filters</span>
  <form class='form-group' action='{% url 'feed' %}' method='get'>
    <label for='id_course'>{{filter.form.course.label}}</label>
    {% render_field filter.form.course class+='form-control' %}
    <label for='id_created'>{{ filter.form.created.label }}</label>
    {% render_field filter.form.created class+='form-control' %}
    <label for='id_author'>Author</label>
    {% render_field filter.form.author class+='form-control' %}
    <label for='id_rating'>Rating</label>
    {% render_field filter.form.rating class+='form-control' %}
    <input class='btn btn-md btn-primary btn-block' type="submit" value='Filter Results' />
  </form>
</aside>

<aside class='col-sm-4 pull-right well'>
  <span class='well-header'>Post Distribution</span>
    <canvas id='course-distribution' width="300" height="300"></canvas>
</aside>

{% endblock %}

{% block extra_head %}
<script>
$(document).ready(function(){

  var ctx = $("#course-distribution").get(0).getContext("2d");
  new Chart(ctx).Doughnut({{ chart_data|safe }},{
    animateScale : true,
    segmentShowStroke : true,
  });

  $('#note-drop-submit').click(function(e){
    e.preventDefault();
    $('#note-drop-form-errors').empty();

    var data = new FormData($('#note-drop-form')[0]);

    $.ajax({
      type: "POST",
      url: "{% url 'note_drop' %}",
      enctype: 'multipart/form-data',
      processData: false,
      contentType: false,
      multiple: true,
      data: data
    })
    .done(function(data){
      window.location.replace(data);
    })
    .fail(function(data){
      errors = eval(data.responseText);
      for(var i=0; i < errors.length; i++){
        $('#note-drop-form-errors').append(errors[i] + '</br>');
      }
      $('#note-drop-form-errors').show();
    });
  });

  $('.noted-btn').click(function(){
    var btn = $(this);
    $.post('{% url 'post_options' %}', {'noted_pk': $(this).attr('object')})
      .done(function(data){
        data = JSON.parse(data);
        if(data == true){
          btn.css('color', 'rgb(255, 145, 0)');
        }
        else {
          btn.css('color', 'black');
        }
      });
  });

  $('.up-btn').click(function(){
    $.post('{% url 'post_options' %}', {'up_pk': $(this).attr('object')})
      .done(function(data){
        data = JSON.parse(data);
        update_rating_btns(data);
      });
  });

  $('.down-btn').click(function(){
    $.post('{% url 'post_options' %}', {'down_pk': $(this).attr('object')})
      .done(function(data){
        data = JSON.parse(data);
        update_rating_btns(data);
      });
  });
});

function update_rating_btns(data){
  $('.post-'+data['post_pk'].toString()+' > .post-rating').text(data['rating']);
  if(data['upvote'] == true){
    $('.post-'+data['post_pk'].toString()+' > .up-btn').css('color', 'rgb(255, 145, 0)');
    $('.post-'+data['post_pk'].toString()+' > .down-btn').css('color', 'black');
  }
  else if(data['upvote'] == false){
    $('.post-'+data['post_pk'].toString()+' > .down-btn').css('color', 'rgb(255, 145, 0)');
    $('.post-'+data['post_pk'].toString()+' > .up-btn').css('color', 'black');
  }
  else{
    $('.post-'+data['post_pk'].toString()+' > .down-btn').css('color', 'black');
    $('.post-'+data['post_pk'].toString()+' > .up-btn').css('color', 'black');
  }
}

</script>
{% endblock %}

templates/main/posts.html
{% extends 'base.html' %}

{% block title %}Note by ID{% endblock %}

{% block content %}
<h2 class='page-header'>Note #{{ post.pk }}</h2>
<p class='lead bg-warning'>
  {{ post.content }}
  {% if post.image %}
    <img src='/media/{{ post.image }}' class='img-responsive post-image' />
  {% endif %}
</p>
<table class='table'>
  <tr>
    <td>Author</td>
    <td><a href='{% url 'users' username=post.author %}'>{{ post.author }}</td>
  </tr>
  <tr>
    <td>Course</td>
    <td>{{ post.course }}</td>
  </tr>
  <tr>
    <td>Created On</td>
    <td>{{ post.created }}</td>
  </tr>
  <tr>
    <td>Rating</td>
    <td>{{ post.rating }}</td>
  </tr>
  <tr>
    <td>Is Archived</td>
    <td>{{ post.archived }}</td>
  </tr>
</table>
{% endblock %}

templates/main/profile.html
{% extends 'base.html' %}

{% block title %}{{ request.user }}'s' Profile{% endblock %}

{% block content %}
<h1 class="page-header">{{ request.user }}'s Profile</h1>

<h2>Settings</h2>
<label for='notify-count-input'>Minimum post rating before sending you an email (use 0 to never notify you)</label>
<input id='notify-count-input' type='number' min='0' max='255' placeholder={{ notify_count }} value={{ notify_count }} /> <button class='btn btn-md btn-default' id='notify-count-btn'>Update</button>

<h2>Here are the courses you are following</h2>
{% if courses %}
<table class='table'>
  {% for course in courses %}
  <tr>
    <td>{{ course }}</td>
    <td><button class='btn btn-md btn-default course-handler' value='{{ course.pk }}'>Unfollow</button></td>
  </tr>
  {% endfor %}
</table>
{% else %}
  <div class='alert alert-warning'>
    No results
  </div>
{% endif %}

<a class='btn btn-md btn-primary' href={% url 'state_selection' %}>Add another course</a>

<h2>Here are the schools of the courses you're following</h2>
{% if schools %}
<ul id='school-list'>
{% for school in schools %}
  <li>{{ school.name }} - {{ school.city }}, {{ school.state }}</li>
{% endfor %}
</ul>
{% else %}
  <div class='alert alert-warning'>
    No results
  </div>
{% endif %}

<h2>Here are your Notes</h2>
{% if posts %}
<table class='table'>
{% for post in posts %}
  <tr>
    <td>{{ post }}</td>
    <td><a href='{% url 'posts' post_pk=post.pk %}'>Link</a></td>
    <td><a href='{% url 'post_delete' post_pk=post.pk %}'>Delete</a></td>
  </tr>
{% endfor %}
</table>
{% else %}
  <div class='alert alert-warning'>
    No results
  </div>
{% endif %}

{% endblock %}

{% block extra_head %}
<script>
$(document).ready(function(){

  $('.course-handler').click(function(){
    var clickedButton = $(this);
    $.post('{% url 'profile' %}', {'course_pk': $(this).val(), 'action': $(this).text()})
      .done(function(data){
        flip_button_action(clickedButton)
        reload_schools($('#school-list'), data);
      });
  });
  
  $('#notify-count-btn').click(function(){
    $.post('{% url 'profile' %}', {'notify_count': $('#notify-count-input').val()})
      .done(function(data){
        $('#notify-count-input').attr('placeholder', data);
      });
  });
  
});

function reload_schools(school_list, data){
  school_list.empty();
  data = eval(data);
  for(var i=0; i < data.length; i++){
    school_list.append('<li>' + data[i]['fields']['name'] + ' - ' + data[i]['fields']['city'] + ', ' + data[i]['fields']['state'] + '</li>');
  }
}

function flip_button_action(btn){
  if(btn.text() == 'Unfollow'){
    btn.text('Follow');
  }
  else {
    btn.text('Unfollow');
  }
}
</script>
{% endblock %}

templates/main/starred.html
{% extends 'base.html' %}

{% block title %}Starred Notes{% endblock %}

{% block content %}
  <h1>Here are the notes you starred</h1>
  {% if posts %}
  <table class='table'>
    {% for post in posts %}
      <tr>
        <td>{{ post.post.content }}</td>
        <td>{{ post.post.created }}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <div class='alert alert-warning'>
      No results
    </div>
  {% endif %}
{% endblock %}

{% block extra_head %}
  {# TODO Add print template #}
{% endblock %}